### ISSUE TITLE
Metadata: Tagging

### ISSUE THREAD

**Issue by FChrispz** [tibetan-nlp/soas-corpus#9]
Check if there is any other contributor to add to the POS tagging field for the CT corpus - @heacu

**Comment by heacu** [comment]
Hi @FChrispz, the POS taggers would be the data collectors listed here https://zenodo.org/record/574878, but also probably Nathan W. Hill.

**Comment by FChrispz** [comment]
Ok, Thanks @heacu - I will add these names + Nathan W. Hill
